"""init migration

Revision ID: 872de62af031
Revises: 
Create Date: 2025-06-21 13:10:35.671919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872de62af031'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freelancers',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('job_category', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('experience_level', sa.String(length=100), nullable=False),
    sa.Column('client_region', sa.String(length=100), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('job_completed', sa.SmallInteger(), nullable=False),
    sa.Column('earnings_USD', sa.SmallInteger(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('job_success_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('client_ration', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('job_duration_days', sa.SmallInteger(), nullable=False),
    sa.Column('project_type', sa.Enum('FIXED', 'HOURLY', name='projecttype'), nullable=False),
    sa.Column('rehire_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('marketing_spend', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freelancers_client_region'), 'freelancers', ['client_region'], unique=False)
    op.create_index(op.f('ix_freelancers_experience_level'), 'freelancers', ['experience_level'], unique=False)
    op.create_index(op.f('ix_freelancers_job_category'), 'freelancers', ['job_category'], unique=False)
    op.create_index(op.f('ix_freelancers_payment_method'), 'freelancers', ['payment_method'], unique=False)
    op.create_index(op.f('ix_freelancers_platform'), 'freelancers', ['platform'], unique=False)
    op.create_index(op.f('ix_freelancers_project_type'), 'freelancers', ['project_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_freelancers_project_type'), table_name='freelancers')
    op.drop_index(op.f('ix_freelancers_platform'), table_name='freelancers')
    op.drop_index(op.f('ix_freelancers_payment_method'), table_name='freelancers')
    op.drop_index(op.f('ix_freelancers_job_category'), table_name='freelancers')
    op.drop_index(op.f('ix_freelancers_experience_level'), table_name='freelancers')
    op.drop_index(op.f('ix_freelancers_client_region'), table_name='freelancers')
    op.drop_table('freelancers')
    # ### end Alembic commands ###
